// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dependencies/db.go

// Package mocks is a generated GoMock package.
package mocks

import (
	dependencies "astroboy/internal/dependencies"
	context "context"
	reflect "reflect"

	expression "github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	gomock "github.com/golang/mock/gomock"
)

// MockIDatabase is a mock of IDatabase interface.
type MockIDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseMockRecorder
}

// MockIDatabaseMockRecorder is the mock recorder for MockIDatabase.
type MockIDatabaseMockRecorder struct {
	mock *MockIDatabase
}

// NewMockIDatabase creates a new mock instance.
func NewMockIDatabase(ctrl *gomock.Controller) *MockIDatabase {
	mock := &MockIDatabase{ctrl: ctrl}
	mock.recorder = &MockIDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabase) EXPECT() *MockIDatabaseMockRecorder {
	return m.recorder
}

// ClearTable mocks base method.
func (m *MockIDatabase) ClearTable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTable indicates an expected call of ClearTable.
func (mr *MockIDatabaseMockRecorder) ClearTable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTable", reflect.TypeOf((*MockIDatabase)(nil).ClearTable), ctx)
}

// PutItem mocks base method.
func (m *MockIDatabase) PutItem(ctx context.Context, input interface{}, expr *expression.Expression) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutItem", ctx, input, expr)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutItem indicates an expected call of PutItem.
func (mr *MockIDatabaseMockRecorder) PutItem(ctx, input, expr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutItem", reflect.TypeOf((*MockIDatabase)(nil).PutItem), ctx, input, expr)
}

// QueryWithIndex mocks base method.
func (m *MockIDatabase) QueryWithIndex(ctx context.Context, indexName string, expr expression.Expression) (dependencies.DbQueryOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithIndex", ctx, indexName, expr)
	ret0, _ := ret[0].(dependencies.DbQueryOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithIndex indicates an expected call of QueryWithIndex.
func (mr *MockIDatabaseMockRecorder) QueryWithIndex(ctx, indexName, expr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithIndex", reflect.TypeOf((*MockIDatabase)(nil).QueryWithIndex), ctx, indexName, expr)
}
