version: "3"
services:
  localstack:
    image: localstack/localstack
    container_name: "my_localstack"
    network_mode: bridge
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"